住宅: ["ﾌﾚﾂｸｽｼﾖｳｶﾞｸﾀﾝｷﾎｹﾝ"]
家具・家電: ["お弁当グッズのカラフルボックス","ショップ木村","タープ＆テントのスマイルプライ","トミダライティング","ニトリ","ニトリネット","ビーベストショップ","ベッド通販専門店ネルコ","ペットエコ＆ザガーデン楽天市場","メンズファッション【ＧＥＮＥＬ","ユナイテッドモール","リコメン堂生活館","ロックビューティー","丸紅フォレストリンクス直売店","千趣会　ベルメゾン","快適エレキング","無印良品","甲陽電産　楽天市場店","総合通販ＰＲＥＭＯＡ　楽天市場","美味しさは元気の源　【自然の館","美容ベビーギフトｓｅｌｅｃｔ","Ｊｏｓｈｉｎｗｅｂ家電とＰＣの","ＳＫＹＵＮＩＣＯ","ＳＳＧ　楽天市場店","ｃｏｍｈｏｍａ楽天市場店","ﾕﾆｸﾛ","ｾｵｻｲｸﾙ ﾋｶﾞｼｼﾞﾕｳｼﾞ","ﾘﾖｳﾌﾟﾗ-ｼﾞﾕ ｱｸﾛｽﾌﾟ"]
交通: ["JRﾄｳｶｲﾂｱ-ｽﾞ WEBｻｲ","ｼﾞｴｲｱ-ﾙﾄｳｶｲ","モバイル　Ｓｕｉｃａ"]
趣味: ["AMAZON DOWNLOADS","AMAZON.CO.JP","APPLE COM BILL","GOOGLE PLAY JAPAN","GOOGLE*COLABORATORY利用国SG","GOOGLE*COLAB利用国SG","東京ディズニーリゾート"]
プレゼント: ["ゆにでのこづち",
    "イッティ公式　楽天市場店",
    "イーベストＰＣ・家電館",
    "ジャパネットたかた",
    "ダイヤモンド褒賞の野沢農産",
    "山梨県笛吹市",
    "フールー",]
食費: ["お米屋しんちゃん",
    "米問屋　金子商店　楽天市場店",
    "西友",
    "ｺﾓﾃﾞｲｲｲﾀﾞ ﾋｶﾞｼｼﾞﾕ",
    "ｻﾐﾂﾄｽﾄｱｵｳｼﾞｻｸﾗﾀﾞﾄ",
    "ｻﾝﾄﾞﾗﾂｸﾞ",
    "ｼﾞﾔﾊﾟﾝﾐ-ﾄｵﾛｼｳﾘｲﾁﾊ",
    "ﾀﾞｲｴｰｱｶﾊﾞﾈ",
    "ﾀﾞｲｴｰﾄｼﾏﾀﾞﾝﾁ",
    "ﾀﾞｲｿ-",
    "ﾋﾞｰｱﾝﾄﾞﾃﾞｲｰﾄﾞﾗﾂｸﾞ",
    "ﾍﾞﾙｸｱﾀﾞﾁｼﾝﾃﾞﾝﾃﾝ",
    "ﾏｲﾊﾞｽｹﾂﾄ ｶﾐﾔ2ﾁﾖｳﾒ",
    "ﾏﾂﾓﾄｷﾖｼﾁｴ-ﾝﾊﾟﾊﾟｽｵ"]
通信費: ["ドコモご利用料金","ＮＥＸＴ"]
投資: ["投信積立（楽天証券）"]
自己研鑽: ["文教堂書店","楽天ブックス"]
水道電気ガス: ["水道","ｿﾌﾄﾊﾞﾝｸﾃﾞﾝｷ","ﾆﾁｶﾞｽ"]
ご褒美: ["楽天ＳＰ　ファミリーマートアプリ",
  "楽天ＳＰ　ローソン　アプリ",
  "楽天ＳＰ　ローソンアプリ",
  "楽天ＳＰ　楽天ペイアプリセブン－イレブン",
  "楽天ＳＰ　西友／ＬＩＶＩＮ／サニーアプリ",
  "ｱﾏｿﾞﾝﾌﾟﾗｲﾑｶｲﾋ",
  "ｸﾞﾂｽﾞﾋﾅﾀｻﾞｶ46",
  "ﾁｹﾂﾄﾋﾟｱ",
  "ﾄｳｷﾖｳﾃﾞｲｽﾞﾆ-ﾘｿﾞ-ﾄ",
  "ｽﾃｰｼﾞｸﾗｳﾄﾞ",
  "ｾﾌﾞﾝｲﾚﾌﾞﾝ.ｼﾞﾔﾊﾟﾝ",]
